force-app/main/default/objects/Universal_App__mdt/Universal_App__mdt.object-meta.xml
<CustomObject>
    <label>Universal App</label>
    <pluralLabel>Universal Apps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Universal_App__mdt/fields/Boolean_Field__c.field-meta.xml
<CustomField>
    <fullName>Boolean_Field__c</fullName>
    <label>Boolean Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Universal_App__mdt/fields/CSS__c.field-meta.xml
<CustomField>
    <fullName>CSS__c</fullName>
    <label>CSS</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Universal_App__mdt/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Universal_App__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Salesforce Object API Name</description>
    <inlineHelpText>API name of standard or custom object (Account, Contact, Custom__c, etc.).</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Universal_App__mdt/fields/Object_with_Boolean__c.field-meta.xml
<CustomField>
    <fullName>Object_with_Boolean__c</fullName>
    <label>Object with Boolean</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Universal_App__mdt/fields/Page_Redirect__c.field-meta.xml
<CustomField>
    <fullName>Page_Redirect__c</fullName>
    <label>Page Redirect</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Universal_App__mdt/fields/Page_Redirect_if_False__c.field-meta.xml
<CustomField>
    <fullName>Page_Redirect_if_False__c</fullName>
    <label>Page Redirect if False</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Universal_App__mdt/fields/Page_Redirect_if_True__c.field-meta.xml
<CustomField>
    <fullName>Page_Redirect_if_True__c</fullName>
    <label>Page Redirect if True</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Universal_App__mdt/fields/Post_Submit_Fields__c.field-meta.xml
<CustomField>
    <fullName>Post_Submit_Fields__c</fullName>
    <inlineHelpText>Enter a JSON formatted map of the record&apos;s field API names to values (i.e. {&quot;Name&quot;:&quot;Valued Account&quot;}) that will be populated during submission.</inlineHelpText>
    <label>Post Submit Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/Universal_App_Section__mdt.object-meta.xml
<CustomObject>
    <label>Universal App Section</label>
    <pluralLabel>Universal App Sections</pluralLabel>
</CustomObject>

force-app/main/default/objects/Universal_App_Section__mdt/fields/conditionalRender__c.field-meta.xml
<CustomField>
    <fullName>conditionalRender__c</fullName>
    <inlineHelpText>JSON object example, keys are required:
{ 
    &quot;Fields&quot;: [
        {
         &quot;controllingField&quot;: &quot;Field that controls the rendering of another section&quot;,
         &quot;controllingValue&quot;: &quot;Value that controls the rendering of another section&quot;,
         &quot;actionSections&quot;: [ &quot;List of Universal App Sections (api names)&quot; ]
        }
    ]
}</inlineHelpText>
    <label>Conditional Render</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/fields/conditionalRequire__c.field-meta.xml
<CustomField>
    <fullName>conditionalRequire__c</fullName>
    <inlineHelpText>JSON object example, keys are required:
{ &quot;Fields&quot;: [
    {
     &quot;api&quot;: &quot;Field To Require API Value&quot;,
     &quot;controllingField&quot;: &quot;Controlling Field API Value&quot;,
     &quot;controllingValues&quot;: [ &quot;List of controlling values&quot; ]
    },
    {
    Repeat the above for more values ie:
    &quot;api&quot;: &quot;RequredAPI&quot;,
    &quot;controllingField&quot;: &quot;RequiredController&quot;,
    &quot;controllingValues&quot;: [&quot;Value1&quot;, &quot;Value2&quot;, &quot;etc...&quot;]
    } ]
}</inlineHelpText>
    <label>Conditional Require</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/fields/DisplayByDefault__c.field-meta.xml
<CustomField>
    <fullName>DisplayByDefault__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Display by Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Determines where in the page (vertical stack descending) this section will appear.</description>
    <inlineHelpText>Determines where in the page (vertical stack descending) this section will appear.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <description>Determines which page of the Universal App this section will appear on.</description>
    <inlineHelpText>Determines which page of the Universal App this section will appear on.</inlineHelpText>
    <label>Page</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/fields/Section_Body__c.field-meta.xml
<CustomField>
    <fullName>Section_Body__c</fullName>
    <description>See LWC Developer Guide for supported HTML tags, under lightning-formatted-rich-text. Auto-links URLs and emails.</description>
    <inlineHelpText>Text displayed under the header (formatted rich text), supporting the following HTML tags: a, b, br, code, div, em, h1, img, li, table, ul, etc.</inlineHelpText>
    <label>Section Body</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/fields/Section_Field_Columns__c.field-meta.xml
<CustomField>
    <fullName>Section_Field_Columns__c</fullName>
    <defaultValue>&quot;2&quot;</defaultValue>
    <inlineHelpText>Number of columns to display in the section.</inlineHelpText>
    <label>Section Field Columns</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/fields/Section_Field_Flow__c.field-meta.xml
<CustomField>
    <fullName>Section_Field_Flow__c</fullName>
    <inlineHelpText>Determines the order in which field set fields display (from left to right in rows, or top down in columns).</inlineHelpText>
    <label>Section Field Flow</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left Right</fullName>
                <default>true</default>
                <label>Left Right</label>
            </value>
            <value>
                <fullName>Top Down</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/fields/Section_Field_Set__c.field-meta.xml
<CustomField>
    <fullName>Section_Field_Set__c</fullName>
    <description>API developer name of the Universal App Object&apos;s field set.</description>
    <inlineHelpText>Field set API name can be found in the &quot;Field Sets&quot; section of the specified Object in &quot;Object Manager&quot; under &quot;Setup&quot;.</inlineHelpText>
    <label>Section Field Set</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/fields/Section_Header__c.field-meta.xml
<CustomField>
    <fullName>Section_Header__c</fullName>
    <label>Section Header</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Universal_App_Section__mdt/fields/Universal_App__c.field-meta.xml
<CustomField>
    <fullName>Universal_App__c</fullName>
    <label>Universal App</label>
    <referenceTo>Universal_App__mdt</referenceTo>
    <relationshipLabel>Universal App Sections</relationshipLabel>
    <relationshipName>Universal_App_Sections</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/UniversalApp.cls
// RadianHub - Developer p.hart
// Apex class for a LWC based universal application dependent on  custom metadata and object field sets

public with sharing class UniversalApp {
	public final static String NOT_FOUND = 'Application \'DeveloperName\' not found in Custom Metadata.';
	public final static String NO_SECTION = 'Application sections were not found in Custom Metadata.';
	public final static String NO_FIELDSETS = 'Field sets were not found for object: {0}.';
	public final static String NULL_FIELDSETS = 'The field set(s) were not found for the following Universal App Sections: {0}.';

	public static Universal_App__mdt[] apps;
	public static Universal_App_Section__mdt[] sects;

	// Method   - queryApps
	// Descr.   - Segregated (for testing) mdt query which updates the class static variable "apps"
	// Input    - String DeveloperName of CustomMetadata 'Universal App'
	private static void queryApps(String appDevName) {
		apps = [
			SELECT 
				Id, 
				CSS__c, 
				DeveloperName, 
				Logo_URL__c, 
				MasterLabel, 
				Object__c, 
				Post_Submit_Fields__c, 
				Page_Redirect__c, 
				Object_with_Boolean__c, 
				Boolean_Field__c, 
				Page_Redirect_if_True__c, 
				Page_Redirect_if_False__c
			FROM Universal_App__mdt
			WHERE DeveloperName = :appDevName
		];
	}

	// Method   - querySects
	// Descr.   - Segregated (for testing) mdt query which updates the class static variable "sects"
	// Input    - Id of 'Universal App'
	private static void querySects(String appId) {
		sects = [
			SELECT
				Id,
				DeveloperName,
				MasterLabel,
				Order__c,
				Page__c,
				Section_Body__c,
				Section_Field_Set__c,
				Section_Field_Columns__c,
				Section_Field_Flow__c,
				Section_Header__c,
				conditionalRequire__c,
				conditionalRender__c,
				DisplayByDefault__c
			FROM Universal_App_Section__mdt
			WHERE Universal_App__c = :appId
		];
	}

	/**
	* @description : Query all fields in a sObject and return the results.
	* @author Zachary Csotya | 06/28/2022 
	* @param Id rId 
	* @param String objName 
	* @return sObject 
	**/
	public static sObject queryRecord(Id rId, String objName) {
		Map<String, Schema.SObjectField> fields = ((SObject) Type.forName('Schema', objName)?.newInstance())?.getSObjectType()?.getDescribe()?.fields?.getMap();

		String expr = ' ';
		SObject obj = null;
		for (Integer i = 0 ; i < fields.values().size() - 1 ; i++) {
			expr += fields.values()[i] + ', ';
		}
		expr += fields.values()[fields.values().size() - 1];
		String qry = 'SELECT' + expr + ' FROM ' + objName + ' WHERE Id = ' + '\'' + rId + '\'';
		obj = Database.query(qry);

		return obj;
	}

	/**
	* @description : Query all fields in a sObject and return the results.
	* @author Zachary Csotya | 08/02/2022 
	* @param String fieldName
	* @param String objName 
	* @param String recordId 
	* @return sObject 
	**/
    @AuraEnabled
	public static sObject queryForBoolean(String fieldName, String objName, String recordId) {
		List<SObject> obj = null;
		String qry = 'SELECT ' + fieldName + ' FROM ' + objName + ' WHERE Id = ' + '\'' + recordId + '\'';
        system.debug(qry);
		obj = Database.query(qry);
        system.debug('Queried Records '+obj.size());

        if (obj.size() == 1) {
            return obj[0];     
        } else {
            return null;
        }
	}

	// Method   - retrieveApp
	// Descr.   - Aura enabled (LWC c-univ-app) method for returning map of Universal Application and field sets
	// Input    - String DeveloperName of CustomMetadata 'Universal App'
	// Output   - Map<String, Object> {'data' -> [{api -> fieldAPI__c, options...}, ...], 'error' -> 'String'}
	@AuraEnabled(cacheable=true)
	public static Map<String, Object> retrieveApp(String appDevName, Id recordId) {
		Map<String, Object> ret = new Map<String, Object>();

		try {
			// Query for application, prepopulate in testing
			if (apps == null) {
				queryApps(appDevName);
			}

			if (apps == null || apps.size() != 1) {
				ret.put('error', NOT_FOUND);
			} else {
				Universal_App__mdt application = apps[0];

				// Query for sections, prepopulate in testing
				if (sects == null) {
					querySects(application.Id);
				}

				if (sects == null || sects.size() == 0) {
					ret.put('error', NO_SECTION);
				} else {
					Map<String, List<Object>> fieldsetmap = new Map<String, List<Object>>();

					Map<String, Schema.FieldSet> objectFieldSetMap = ((SObject) Type.forName('Schema', application.Object__c)?.newInstance())
						?.getSObjectType()
						?.getDescribe()
						?.fieldSets
						?.getMap();

					if (objectFieldSetMap == null) {
						ret.put('error', String.format(NO_FIELDSETS, new List<Object>{ application.Object__c }));
					} else {
						Map<String, Set<String>> mapfieldset = new Map<String, Set<String>>();

						for (Universal_App_Section__mdt s : sects) {
							String sfs = s.Section_Field_Set__c;
							if (String.isNotBlank(sfs)) {
								if (mapfieldset.containsKey(sfs)) {
									mapfieldset.get(sfs).add(s.DeveloperName);
								} else {
									mapfieldset.put(sfs, new Set<String>{ s.DeveloperName });
								}
							}
						}

						Set<String> nullFieldSets = new Set<String>();
						sObject fieldValues = null;

						if (recordId != null) {
							fieldValues = queryRecord(recordId, application.Object__c);
							system.debug(fieldValues);
						}

						for (String fs : mapfieldset.keySet()) {
							Schema.FieldSet objFieldSet = objectFieldSetMap.get(fs);
							if (objFieldSet != null) {
								List<Schema.FieldSetMember> fields = objFieldSet.getFields();
								List<Object> fieldMembers = new List<Object>();
								for (Schema.FieldSetMember member : fields) {
									Map<String, Object> fieldMember = new Map<String, Object>{
										'api' => member.getFieldPath(),
										'req' => (member.getDBRequired() || member.getRequired()),
										'label' => member.getLabel(),
										'type' => member.getType().name()
									};	
									if (recordId != null) {
										fieldMember.put('value', fieldValues.get(member.getFieldPath()));
									}
									fieldMembers.add(fieldMember);
								}
								fieldsetmap.put(fs, fieldMembers);
							} else {
								nullFieldSets.addAll(new List<String>(mapfieldset.get(fs)));
							}
						}
						system.debug(fieldsetmap);

						if (nullFieldSets.size() > 0) {
							ret.put('error', String.format(NULL_FIELDSETS, new List<Object>{ nullFieldSets }));
						}

						ret.put('data', new Map<String, Object>{ 'application' => application, 'sections' => sects, 'fieldsetmap' => fieldsetmap });
					}
				}
			}
		} catch (Exception e) {
			ret.put('error', e.getTypeName() + ' | ' + e.getMessage() + ' | ' + e.getStackTraceString());
		}

		return ret;
	}

	@AuraEnabled
	public static Map<String, Object> submitApp(SObject sObj) {
		Map<String, Object> ret = new Map<String, Object>();

		try {
			upsert sObj;
			ret.put('data', sObj.Id);
		} catch (Exception e) {
			ret.put('error', e.getTypeName() + ' | ' + e.getMessage() + ' | ' + e.getStackTraceString());
		}

		return ret;
	}
}